
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
from Camembert import *


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("Moteur de recherche")

window.geometry("682x433")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 433,
    width = 682,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

def affichage_reponse(event=None):
    question = entry_1.get("1.0", "end-1c")
    print("ff")
    # Supprimer le texte existant sur le canevas s'il existe
    texts_and_similarities = find_top_texts(question, model, dict_embeddings, dict_sol_copy)
    texte = ""  # Initialiser la variable texte en tant que chaîne de caractères vide
    for num_texte, similarity, text in texts_and_similarities:
        print("Numéro de texte:", num_texte)
        print("Similarité:", similarity)
        print("Texte associé:", text)
        print()  # Ajouter une ligne vide entre chaque texte et solution
        texte += "\n " + str(num_texte) +  ": " + str(text)  # Ajouter le numéro de texte à la chaîne
    canvas.delete("reponse_texte")
    canvas.create_text(
        137.0,
        276.0,
        anchor="nw",
        text="Les codes correspondants sont : " + texte,
        fill="#FFFFFF",
        font=("Judson Regular", 12 * -1),
        tags="reponse_texte",
        width=400
    )

    
canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    341.0,
    216.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    625.0,
    216.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    57.0,
    216.0,
    image=image_image_3
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=affichage_reponse,
    relief="flat"
)
button_1.place(
    x=285.0,
    y=191.0,
    width=111.17572021484375,
    height=42.0
)


canvas.create_text(
    229.0,
    32.0,
    anchor="nw",
    text="Moteur de recherche\n",
    fill="#FFFFFF",
    font=("Judson Regular", 24 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    341.0,
    122.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#D2C6C6",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=204.0,
    y=97.0,
    width=274.0,
    height=49.0
)
window.resizable(False, False)
window.mainloop()
