from codecarbon import EmissionsTracker

tracker = EmissionsTracker()
tracker.start()

# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from ecolo import *


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("Gain Par code")

window.geometry("682x433")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 433,
    width = 682,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

def affichage_reponse(event=None):
    texte = entry_1.get("1.0", "end-1c")
    print("ff")
    lis=[]
    print(int(texte))
    lis.append(int(texte))
     # Supprimer le texte existant sur le canevas s'il existe
    canvas.delete("reponse_texte")
    tempo=final_eco(f4(f3(lis)))
    tempo[0][0]=round(tempo[0][0], 2)
    tempo[0][1]=round(tempo[0][1], 2)
    tempo[0][2]=round(tempo[0][2], 2)
    print("teste",str(tempo[0][2]))

    canvas.create_text(
        137.0,
        276.0,
        anchor="nw",
        text="Le Gain financier est : "+str(tempo[0][0])+"€\n"+"L'économie d'énergie : "+str(tempo[0][1])+"KWh\n"+"Les émissions GES évitées : "+str(tempo[0][2])+" t de CO2",
        fill="#FFFFFF",
        font=("Judson Regular", 15 * -1),
        tags="reponse_texte",
        width=395
    )
    
canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    341.0,
    216.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    625.0,
    216.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    57.0,
    216.0,
    image=image_image_3
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=affichage_reponse,
    relief="flat"
)
button_1.place(
    x=285.0,
    y=191.0,
    width=111.17572021484375,
    height=42.0
)


canvas.create_text(
    209.0,
    32.0,
    anchor="nw",
    text="Donnez votre nombre\n",
    fill="#FFFFFF",
    font=("Judson Regular", 24 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    341.0,
    122.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#D2C6C6",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=204.0,
    y=97.0,
    width=274.0,
    height=49.0
)
window.resizable(False, False)
window.mainloop()
emissions: float = tracker.stop()
print(f"Emissions: {emissions} kg ")
