version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Lebonmdp1!sql
      MYSQL_DATABASE: Databattle
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d  # Mount data.sql for initialization

  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Lebonmdp1!sql
      - MYSQL_DB=Databattle

volumes:
  db_data:
