FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*


# Copy project files
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Download the fr_core_news_md spaCy model
RUN python -m spacy download fr_core_news_md

EXPOSE 5000

CMD ["python", "Camembert.py"]

